export const THEMES_LIST = [
  'black',
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
];

export const PREVIEW_THEME_MESSAGES = [
  {
    id: '1',
    message: 'Hello, how are you?',
    sender: 'John Doe',
    createdAt: '2023-01-01T00:00:00.000Z',
    isSent: true,
  },
  {
    id: '2',
    message: 'I am doing well, thank you for asking. You?',
    sender: 'Jane Doe',
    createdAt: '2023-01-02T00:00:00.000Z',
    isSent: false,
  },
  {
    id: '3',
    message: 'I am good too, thanks for asking.',
    sender: 'John Doe',
    createdAt: '2023-01-03T00:00:00.000Z',
    isSent: true,
  },
];
